- name: configure netplan
  template:
    src: netplan.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
    mode: '0644'

- name: apply netplan
  command: netplan try --timeout 20
  ignore_errors: yes

- debug: msg="{{ net_source_name }} renamed to {{ net_desired_name }}"
