- name: luks format
  community.crypto.luks_device:
    device: "{{ crypto_partition }}"
    name: crypt_data
    state: opened
    passphrase: "{{ luks_passphrase }}"
    type: luks2

- name: create filesystem
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/mapper/crypt_data

- name: ensure mountpoint exists
  file:
    path: /mnt/crypted
    state: directory

- name: mount luks
  mount:
    path: /mnt/crypted
    src: /dev/mapper/crypt_data
    fstype: ext4
    state: mounted
